spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: dev_user
    password: dev_pass
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dislect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false